### ISSUE TITLE
Guidance Needed for Porting to Web

### ISSUE THREAD

**Issue by tanishqmanuja** [Kyant2021/Monet#1]
Actually, this library is so good that i want to port it for web apps . I have been using it on android for a while ( ofcourse without understanding the magic it does to color) . I understand some basic color schema like rgb, hex, srgb but this CAM logic and the XYZ reference is way above my current skill level .. can u guide me to a decent logic by which i can port this. I dont want to port the wallpaper color extraction or anything only this logic where it spits the monet color palette from single rgb/hex color

Thank you in advance.
Also if you are busy atm you can close this issue right away ( no hard feelings 😅)

**Comment by Kyant2021** [comment]
Did you mean to the implementation of JavaScript? Kotlin is similar to JS, so you can try to convert kt to JS in person.

**Comment by Kyant2021** [comment]
I am not available in the long period, and without computer, so I can't help you.

**Comment by tanishqmanuja** [comment]
Yeah javascript port . Actually i just need conceptual help only .I cant trace which functions are for the color implementation and which are for the color detection from image file.

**Comment by tanishqmanuja** [comment]
https://github.com/tanishqmanuja/monet.js
